# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "swift"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      swift-minor-fluent:
        update-types:
          - "patch"
          - "minor"
        patterns:
          - "gtihub.com/vapor/fluent*"
      swift-minor-queues:
        update-types:
          - "patch"
          - "minor"
        patterns:
          - "gtihub.com/vapor/queues*"
      swift-minor-vapor:
        update-types:
          - "patch"
          - "minor"
        patterns:
          - "gtihub.com/vapor/*"
      swift-minor:
        update-types:
          - "patch"
          - "minor"
        patterns:
          - "*"
      swift-major:
        update-types:
          - "major"
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
