name: Build Development Containers Image

on:
  push:
    branches: [ master ]
    paths:
      - ".github/workflows/devcontainer.yml"
      - ".devcontainer/Dockerfile"
  schedule:
    - cron: '30 4 * * 1'

concurrency:
  group: 'devcontainer'
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-devcontainer


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest

      - name: Build builder Docker image
        id: builder
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:.devcontainer"
          platforms: ${{ env.IMAGE_ARCH }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
